### ISSUE TITLE
question for video spliting

### ISSUE THREAD

**Issue by zhangyongshun** [shaodong233/open-sora-Dataset#3]
Thanks for the wonderful work! I am confused with the video splitting pipeline. 
    
According to the readme and my comprehension,  the videos are splitted by Panda70M to get the no-transition clips, firstly, and then these clips are further splitted to get the final 2s clips.  

Is that right?

**Comment by DachengLi1** [comment]
Same question. @zhangyongshun Did you get the answer? Thank you!

If I understand correctly, the videos are simply spllited by no_transition.py since their videos are single scenes?

**Comment by zhangyongshun** [comment]
> Same question. @zhangyongshun Did you get the answer? Thank you!
> 
> If I understand correctly, the videos are simply spllited by no_transition.py since their videos are single scenes?

yes. after downloading and analyzing the dataset, i find it is actually the way i described above
